spring.application.name=queuebite
spring.datasource.url=jdbc:mysql://localhost:3306/queuebite
spring.datasource.username=root
spring.datasource.password=Rohit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080